# Generated by Django 2.2.5 on 2024-07-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20240724_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
